name: Build and Deploy app to Azure

on:
  push:
    branches:
      - main

env:
  AZURE_APP_NAME: "trade-compas"
  APP_PACKAGE_PATH: "."
  NETCORE_VERSION: "8.0"

jobs:
  build:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET Core SDK ${{ env.NETCORE_VERSION }}
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.NETCORE_VERSION }}

      - name: Restore
        run: dotnet restore

      - name: Build
        run: dotnet build -c Release --no-restore

      - name: Publish app for deploy
        run: dotnet publish --no-build -c Release -o ${{ env.APP_PACKAGE_PATH }}

      - name: Deploy to Azure WebApp
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_APP_NAME }}
          publish-profile: ${{ secrets.AZURE_APP_PUBLISH_PROFILE }}
          package: ${{ env.APP_PACKAGE_PATH }}